### ISSUE TITLE
`marginaleffects::get_predict()` will return `estimate` instead of `predicted`

### ISSUE THREAD

**Issue by vincentarelbundock** [IQSS/clarify#6]
Just a heads-up that the next version of `marginaleffects` will introduce some breaking changes. In particular, all the data frames returned will follow the `broom` convention of returning an `estimate` column instead of function-specific column names `predicted`, `comparison`, `marginalmean`, `dydx`.

This also affects internal functions like `get_predict()`, which may be used in this package.

Sorry!

**Comment by ngreifer** [comment]
Thank you! Just made changes to the development version to accommodate this. `clarify` should now work whether the user is using an older or new version of `marginaleffects`.
